name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
    paths:
      - './frontend/**'
      - './Trunk.toml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - './frontend/**'
      - './Trunk.toml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Cache Cargo ðŸ“¦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rustfmt, clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
          override: true

      - name: rustup target add wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install trunk ðŸ§³
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: 'latest'

      - name: cargo fmt --all -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: cargo test --release --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features


      - name: Build Web App
        run: |
          trunk build --release

      - uses: actions/upload-artifact@v2
        with:
          name: webapp_artifact
          path: |
            frontend/dist
  # deploy:
  #   needs: [build]
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Deploy Job
  #   steps:
  #     - name: Download Web App ðŸ“¦
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: webapp_artifact
  #         path: ./
  #     - name: Deploy ðŸš€
  #       id: deploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
  #         action: "upload"
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: "/" # App source code path
  #         api_location: "" # Api source code path - optional
  #         output_location: "dist" # Built app content directory - optional
  #         ###### End of Repository/Build Configurations ######

  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request ðŸš«
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         action: "close"
